apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  generateName: posthook-test-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  job_template_name: Demo Job Template
  tower_auth_secret: toweraccess
